### ISSUE TITLE
CentOS 7 installation fails without EPEL

### ISSUE THREAD

**Issue by joerocklin** [opscode-cookbooks/erlang#24]
As reported in jjasghar/rabbitmq#189 - the erlang package fails to install due to changes in dependent package availability. Adding the `yum-epel` recipe resolves the issue.

**Comment by drag00n** [comment]
This seems to be similar to rhel 5. Fix incoming

**Comment by drag00n** [comment]
This will probably also fix [rabbitmq on centos 7](https://github.com/jjasghar/rabbitmq/issues/189)
